language: ruby
dist: trusty

addons:
  apt:
    packages:
    - shellcheck

before_script:
  - mkdir -p /tmp/local
  - git clone https://github.com/bats-core/bats-core.git /tmp/bats
  - /tmp/bats/install.sh /tmp/local
  - export PATH+=:/tmp/local/bin

script:
  - test/shellcheck
  - test/run_tests
