language: bash
sudo: required

services:
  - docker

dist: trusty
branches:
  only:
    - master
    - develop

env:
  - BASH_VAR=3.2
  - BASH_VAR=4.0
  - BASH_VAR=4.1
  - BASH_VAR=4.2
  - BASH_VAR=4.3
  - BASH_VAR=4.4
before_script:
  - docker build ./ -t kawazu_bash_$BASH_VAR

script:
  - docker run --rm kawazu_bash_$BASH_VAR /tmp/kawazu/test/run_tests
  - docker run --rm kawazu_bash_$BASH_VAR /tmp/kawazu/test/shellcheck
notifications:
  email: never
